title: budget-tracker
name: Budget Tracker
description: A simple budget tracker built with vanilla JavaScript, HTML5, and CSS.
company: Cyberdime Development
author: John Norris
email: info@cyberdime.io
github: https://github.com/cyberdime-dev
linkedin: https://www.linkedin.com/in/cyberdime-dev
